In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from google.colab import files
uploaded=files.upload()

Saving AAPL.xlsx to AAPL (1).xlsx

In [3]:
df = pd.read_excel("AAPL.xlsx")

In [4]:
print("First 5 Rows:")
display(df.head())

First 5 Rows:

,Date,Open,High,Low,Close,Adj Close,Volume
0,2014-09-29,100.589996,100.690002,98.040001,99.620003,93.514290,142718700
1,2014-10-06,99.949997,102.379997,98.309998,100.730003,94.556244,280258200
2,2014-10-13,101.330002,101.779999,95.180000,97.669998,91.683792,358539800
3,2014-10-20,98.320000,105.489998,98.220001,105.220001,98.771042,358532900
4,2014-10-27,104.849998,108.040001,104.699997,108.000000,101.380676,220230600

In [5]:
print("\nLast 5 Rows:")
display(df.tail())

Last 5 Rows:

,Date,Open,High,Low,Close,Adj Close,Volume
179,2018-03-05,175.210007,180.000000,174.270004,179.979996,179.979996,139852700
180,2018-03-12,180.289993,183.500000,177.619995,178.020004,178.020004,155417500
181,2018-03-19,177.320007,177.470001,164.940002,164.940002,164.940002,172670700
182,2018-03-26,168.070007,175.149994,165.190002,167.779999,167.779999,157898400
183,2018-03-29,167.804993,171.750000,166.899994,167.779999,167.779999,38398505

In [6]:
print("\nDataset information:")
print(df.info())

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 184 entries, 0 to 183
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       184 non-null    datetime64[ns]
 1   Open       184 non-null    float64
 2   High       184 non-null    float64
 3   Low        184 non-null    float64
 4   Close      184 non-null    float64
 5   Adj Close  184 non-null    float64
 6   Volume     184 non-null    int64
dtypes: datetime64[ns](1), float64(5), int64(1)
memory usage: 10.2 KB
None

In [7]:
print("\nDataset shape:")
print(df.shape)

Dataset shape:
(184, 7)

In [8]:
print("\nColumn name:")
print(df.columns)

Column name:
Index(['Date', 'Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume'], dtype='object')

In [9]:
print("\nData types:")
print(df.dtypes)

Data types:
Date         datetime64[ns]
Open                float64
High                float64
Low                 float64
Close               float64
Adj Close           float64
Volume                int64
dtype: object

In [10]:
print("\nmissing values:")
print(df.isnull().sum())

missing values:
Date         0
Open         0
High         0
Low          0
Close        0
Adj Close    0
Volume       0
dtype: int64

In [11]:
print(df.columns.tolist())

['Date', 'Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume']

In [12]:
df = df.sort_values('Date')

In [13]:
df["Daily_Return"] = df["Close"].pct_change() * 100